namespace Models.Composite
{
    public enum Permiso
    {
        EsFamilia,
        Bitacora,
        Gestion_Usuarios,
        Seguridad,
        Restore,
        BackUp,
        GestionFamilia,
        GestionFamiliaPatente,
        GestionPermisosUsuario,
        FalloIntegridad,
        ListarUsuarios,
        RegistroUsuario,
        PermisoUsuario,
        ConfiguracionEmpresas,
        ConfiguracionProducto,
        Productos,
        Carrito,
        MisCompras,
        MiCuenta,
        Reportes,
        ReporteCompras,
        DesbloquearUsuario,
        Documentos,
        CargaDocumentos,
        MisDocumentos,
        DocumentoReporte
    }
}
